### ISSUE TITLE
[gofed-web] scan fails with exception

### ISSUE THREAD

**Issue by ingvagabund** [gofed/gofed-web#1]
> Loading cache
> Geting updates for project cadvisor (git repo)
> 
> > Commit found in cache, using cached results
> > Generating project cadvisor
> > Geting updates for project docker (git repo)
> > Traceback (most recent call last):
> >   File "./gofed-web.py", line 536, in <module>
> >     p['stats'] = getProjectUpdatesGit(projectdir, p, depth, noupdate)
> >   File "./gofed-web.py", line 357, in getProjectUpdatesGit
> >     updateProject(src, project, noupdate)
> >   File "./gofed-web.py", line 273, in updateProject
> >     runCommand("git pull ", src)
> >   File "./gofed-web.py", line 164, in runCommand
> >     raise Exception("Failed to run '" + cmd + "':
> > " + stderr)
> > Exception: Failed to run 'git pull ':
> > From https://github.com/docker/docker
> >    ad91d2e..e137f2d  master     -> origin/master
> > error: unable to resolve reference refs/remotes/origin/release/1.8: Not a directory
> >  ! [new branch]      release/1.8 -> origin/release/1.8  (unable to update local ref)
> > error: some local refs could not be updated; try running
> >  'git remote prune origin' to remove any old, conflicting branches

**Comment by fridex** [comment]
This looks like old (static) gofed-web version. It was replaced.

**Comment by ingvagabund** [comment]
The same exception today as you say from the old web. So the new one is still not sending emails? If so, can you disable sending emails from the old web?
