### ISSUE TITLE
[RFE] Show diff based on fedora commit and godeps.json

### ISSUE THREAD

**Issue by fridex** [gofed/gofed-web#14]
As a maintainer, I would like to see apidiff based on godeps.json, which could be uploaded, and current commit in fedora pkgdb (based on dependencies from godeps.json).

**Comment by fridex** [comment]
Done in https://github.com/gofed/gofed-web/commit/b610c35d17648997e8f4f9e72080948bec84c74b

**Comment by ingvagabund** [comment]
Nice!!!

**Comment by ingvagabund** [comment]
Related https://github.com/gofed/gofed-web/issues/16
