### ISSUE TITLE
[RFE] for a list of apidiffs in "Godeps APIdiff", show only symbols that has changed implicitely (new symbols only when requested, e.g. with a checkbox)

### ISSUE THREAD

**Issue by ingvagabund** [gofed/gofed-web#16]
Between two commits of the same package there can be a lot of new symbols which fill entire display width. These are symbols I will not be interested in seeing in many cases. Would it be possible to show only changed or deleted symbols. And add a button or checkbox to display new symbols? Or divide the table into two parts. First at the top show red symbols, second one at the bottom will show green symbols. What do you think?

**Comment by fridex** [comment]
No problem at all... I can split it into two parts as described.

**Comment by ingvagabund** [comment]
Thanks
