### ISSUE TITLE
Missing changes in API for golang-github-spf13-cobra

### ISSUE THREAD

**Issue by ingvagabund** [gofed/gofed-web#2]
Api changes for golang-github-spf13-cobra shows "No changes found" in each graph. However, when running apidiff on e15d674de659b2514ead6d5b41f3afcb3190fa08 and 5b121bc9fbffd5ba668b5aa101790d4b27917d84, I am getting:

``` vim
$ gofed apidiff e15d674de659b2514ead6d5b41f3afcb3190fa08 5b121bc9fbffd5ba668b5aa101790d4b27917d84 -vc
Package: .
    +AddTemplateFuncs func added
    +AddTemplateFunc func added
```

**Comment by fridex** [comment]
There is scheduled a complete regeneration of the DB using Gofed 0.0.8 (21 August 2015). I've fixed some issues in gofed-web, will see if the problem persists.

**Comment by fridex** [comment]
Should be fixed now.
