### ISSUE TITLE
[RFE] when displaying a graph of commits, show version to which a commit belons

### ISSUE THREAD

**Issue by ingvagabund** [gofed/gofed-web#3]
E.g. for [1] go-systemd project I would to see which version each commit belongs to (if git repository provides such a feature) Via 'git tags' for example or try to derive the version from other information.

[1] http://209.132.179.123/project/golang-github-coreos-go-systemd

**Comment by fridex** [comment]
Good idea!

```
git tag --points-at HEAD
```

and

```
hg log -r "." --template "{latesttag}\n"
```

look suitable.
Thanks!
