### ISSUE TITLE
"Review a spec file" text

### ISSUE THREAD

**Issue by fridex** [gofed/gofed-web#9]
A user can ask for a review of a spec file, see:

http://209.132.179.123/review

We should make a very simple explanation for a user what's going on and how to use this form, e.g.:

> You can submit a spec file and wait for a review. Spec file should respect Fedora packaging guidelines. The best way how to create a spec file is to use gofed. See gofed help - a ready to use Python script prepared to automate packaging and generating spec files. Please state your e-mail so we can contact you!

**Comment by fridex** [comment]
I don't think this is a good way of doing this. We should consider making a step-by-step tut and ask a user to open bugzilla issue; not to make a separate submission. We should centralize reviews and open reviews for a discussion.

**Comment by ingvagabund** [comment]
Aim here was to provide additional information about the spec file. It was more like user will create a review in bugzilla and if he/she want he/she can send us a link to bugzilla. We will run e.g. gofed lint or other scans (which does not have to impemented yet) and send him/her email with the check (or comment the bugzilla). It was not meant as a full replacement of the review itself. At the same time gofed is only recommended way for generating spec files. Not sure if it is the best way as I am afraid the spec file is getting longer and longer. On the other hand it contains more informations for scan and tools that can automatically update the spec file, download new tarball and run additional checks. So if the spec file is generated via gofed, used gets some advantages over manually created spec file.

**Comment by ingvagabund** [comment]
So maybe something like:
"If you are not sure your spec file contains all necessary data, macros or if there is something else you can extend your spec file with, don't hesitate to contact us. We will try to provide you a feedback and help with advanced features (i.e. support for secondary architectures, CI/unit-test testing, macros for automatic updates, etc.).
To get a help from us, please fill the form."

**Comment by fridex** [comment]
OK, so this could be generalized to a simple "get help" form where users could ask anything about packaging and related things.

Your text was added, I will commit modified init data with this text. Thanks!
